package sk.uniba.fmph.dcs.stone_age;

public enum Location {
    TOOL_MAKER, HUT, FIELD, HUNTING_GROUNDS, FOREST, CLAY_MOUND, QUARY, RIVER, CIVILISATION_CARD1, CIVILISATION_CARD2,
    CIVILISATION_CARD3, CIVILISATION_CARD4, BUILDING_TILE1, BUILDING_TILE2, BUILDING_TILE3, BUILDING_TILE4,
}
